
bot_name: 阿晴  #机器人名字，训练功能会用到
start_tip: 阿晴上班了,今天又是充满干劲的一天~   #上班提示语  
close_tip: 阿晴去玩了，开溜~      #下班提示语
start_order: '#阿晴上班'     #机器人上班指令  如需修改，将引号里面的东西换成自己的
close_order: '#阿晴下班'     #机器人下班指令。如需修改，将引号里面的东西换成自己的

poke_switch: false #戳一戳开关,默认false关闭，改成true开启